GET http://localhost:3000/api/providers
Content-Type: application/json

###
GET http://localhost:3000/api/provider/1
Content-Type: application/json

###
DELETE http://localhost:3000/api/provider/1

###
PUT http://localhost:3000/api/provider
Content-Type: application/json

{
  "facilityName": "CityHealth Medical Center",
  "doctorName": "Dr. John Doe",
  "specialty": "General Health Check",
  "availableHours": [
    "5:00"
  ]
}

###
PATCH http://localhost:3000/api/provider
Content-Type: application/json

{
  "facilityName": "CityHealth Medical Center 42",
  "specialty": "General Health Check",
  "id": "2"
}